## EQUAL WEIGHTS STRATEGY

In [5]:
import pandas as pd 
import numpy as np 
import yfinance as yf 
import math

In [6]:
tickers= pd.read_csv('top_50_indian_stocks.csv')
tickers.head()

         Ticker               Company Name
0   RELIANCE.NS        Reliance Industries
1        TCS.NS  Tata Consultancy Services
2   HDFCBANK.NS                  HDFC Bank
3       INFY.NS                    Infosys
4  ICICIBANK.NS                 ICICI Bank

In [7]:
def fetch_market_cap(ticker_list):
    data= yf.download(ticker_list, period='1d', group_by='ticker', auto_adjust=False)
     
    stocks_data = []
    for ticker in ticker_list:
        lastest_price= data[ticker]['Close'].iloc[-1]
        market_cap=yf.Ticker(ticker).info.get('marketCap', 'N/A')

        stocks_data.append(
            {'Ticker': ticker,
             'Market Cap': market_cap,
             'Latest Price': lastest_price, })
        
    return pd.DataFrame(stocks_data)

    


tickers_list=tickers["Ticker"].values.tolist()
df=fetch_market_cap(tickers_list)
df.head()

[********************  42%                       ]  21 of 50 completedHTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TATAMOTORS.NS"}}}
[**********************74%***********            ]  37 of 50 completed$TATAMOTORS.NS: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
[*********************100%***********************]  50 of 50 completed

1 Failed download:
['TATAMOTORS.NS']: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TATAMOTORS.NS"}}}

         Ticker      Market Cap  Latest Price
0   RELIANCE.NS  17862863355904   1320.000000
1        TCS.NS   8312193548288   2297.399902
2   HDFCBANK.NS  11435754127360    742.700012
3       INFY.NS   4867370254336   1202.500000
4  ICICIBANK.NS   8887814062080   1239.699951

In [8]:
df = (
    df[df["Market Cap"] != "N/A"]
    .sort_values(by="Market Cap", ascending=False)
    .reset_index(drop=True)
)

df

           Ticker      Market Cap  Latest Price
0     RELIANCE.NS  17862863355904   1320.000000
1     HDFCBANK.NS  11435754127360    742.700012
2   BHARTIARTL.NS  11029219115008   1810.599976
3    ICICIBANK.NS   8887814062080   1239.699951
4         SBIN.NS   8806932152320    954.099976
5          TCS.NS   8312193548288   2297.399902
6   BAJFINANCE.NS   5528003018752    889.049988
7           LT.NS   5517530365952   4010.800049
8   HINDUNILVR.NS   4897253097472   2084.300049
9         INFY.NS   4867370254336   1202.500000
10   SUNPHARMA.NS   4310405218304   1796.500000
11  ADANIPORTS.NS   4109110870016   1783.500000
12      MARUTI.NS   4070255624192  12946.000000
13    ADANIENT.NS   3988625031168   2909.399902
14    AXISBANK.NS   3967961268224   1275.900024
15   KOTAKBANK.NS   3753795911680    377.399994
16        NTPC.NS   3672127832064    378.700012
17       TITAN.NS   3570002296832   4024.600098
18         M&M.NS   3566503985152   2970.199951
19         ITC.NS   3503865724928    279.649994
20        ONGC.NS   3324967649280    264.299988
21  ULTRACEMCO.NS   3304113307648  11232.000000
22     HCLTECH.NS   3233525268480   1195.099976
23    JSWSTEEL.NS   3171359129600   1299.400024
24   COALINDIA.NS   2912505561088    472.600006
25  BAJAJFINSV.NS   2811616296960   1758.900024
26   POWERGRID.NS   2661367676928    286.149994
27       DMART.NS   2655480446976   4071.800049
28   TATASTEEL.NS   2626197127168    210.570007
29  ASIANPAINT.NS   2523535245312   2632.399902
30  ADANIGREEN.NS   2383299215360   1446.900024
31       WIPRO.NS   2165316255744    206.410004
32      GRASIM.NS   2104098947072   3102.600098
33         IOC.NS   1960028012544    138.800003
34   EICHERMOT.NS   1949069737984   7100.500000
35    DIVISLAB.NS   1739748278272   6553.500000
36  PIDILITIND.NS   1483102224384   1457.199951
37       TECHM.NS   1366840836096   1543.199951
38        BPCL.NS   1268316897280    296.850006
39    HDFCLIFE.NS   1265429643264    586.549988
40   BRITANNIA.NS   1242278133760   5157.500000
41       CIPLA.NS   1123085189120   1390.300049
42     HDFCAMC.NS   1116513107968   2604.699951
43     DRREDDY.NS   1074380341248   1290.400024
44  HEROMOTOCO.NS    964427972608   4819.899902
45    SHREECEM.NS    904183545856  25060.000000
46     HAVELLS.NS    717079969792   1143.199951
47  INDUSINDBK.NS    702115479552    901.150024
48     SBICARD.NS    586143760384    615.950012

Taking top 10 stocks as per marketcap

In [9]:
df=df.head(10)
df.reset_index(drop=True, inplace=True)
df

          Ticker      Market Cap  Latest Price
0    RELIANCE.NS  17862863355904   1320.000000
1    HDFCBANK.NS  11435754127360    742.700012
2  BHARTIARTL.NS  11029219115008   1810.599976
3   ICICIBANK.NS   8887814062080   1239.699951
4        SBIN.NS   8806932152320    954.099976
5         TCS.NS   8312193548288   2297.399902
6  BAJFINANCE.NS   5528003018752    889.049988
7          LT.NS   5517530365952   4010.800049
8  HINDUNILVR.NS   4897253097472   2084.300049
9        INFY.NS   4867370254336   1202.500000

In [10]:
portfolio_size=int(input("Enter the amount you want to invest in your portfolio: "))
position_size=(portfolio_size/len(df))
position_size

10000.0

In [12]:
df['no_of_shares_to_buy']= df['Latest Price'].apply(lambda price: math.floor(position_size/price))
df

          Ticker      Market Cap  Latest Price  no_of_shares_to_buy
0    RELIANCE.NS  17862863355904   1320.000000                    7
1    HDFCBANK.NS  11435754127360    742.700012                   13
2  BHARTIARTL.NS  11029219115008   1810.599976                    5
3   ICICIBANK.NS   8887814062080   1239.699951                    8
4        SBIN.NS   8806932152320    954.099976                   10
5         TCS.NS   8312193548288   2297.399902                    4
6  BAJFINANCE.NS   5528003018752    889.049988                   11
7          LT.NS   5517530365952   4010.800049                    2
8  HINDUNILVR.NS   4897253097472   2084.300049                    4
9        INFY.NS   4867370254336   1202.500000                    8