## VALUE INVESTING

In [ ]:
import pandas as pd 
import numpy as np 
import yfinance as yf 
import math
from scipy import stats

In [2]:
tickers= pd.read_csv('top_50_indian_stocks.csv')
tickers.head()

         Ticker               Company Name
0   RELIANCE.NS        Reliance Industries
1        TCS.NS  Tata Consultancy Services
2   HDFCBANK.NS                  HDFC Bank
3       INFY.NS                    Infosys
4  ICICIBANK.NS                 ICICI Bank

In [16]:
import yfinance as yf
import pandas as pd
import numpy as np

def fetch_values_of_stocks(tickers):
    value_cols = [
        "Ticker",
        "Price",
        "PE-Ratio",
        "PB-Ratio",
        "PS-Ratio",
        "EV/EBITDA-Ratio",
        "EV/GP"
    ]

    value_df = pd.DataFrame(columns=value_cols)

    for ticker in tickers:
        try:
            stock = yf.Ticker(ticker)

            history = stock.history(period="1d")

            if history.empty:
                print(f"{ticker}: no price data")
                continue

            price = history["Close"].iloc[-1]

            financials = stock.financials
            info = stock.info

            pe_ratio = info.get("forwardPE", np.nan)
            pb_ratio = info.get("priceToBook", np.nan)
            ps_ratio = info.get(
                "priceToSalesTrailing12Months",
                np.nan
            )

            ev = info.get("enterpriseValue", np.nan)
            ebitda = info.get("ebitda", np.nan)

            ev_ebitda = (
                ev / ebitda
                if pd.notna(ev)
                and pd.notna(ebitda)
                and ebitda != 0
                else np.nan
            )

            gross_profit = (
                financials.loc["Gross Profit"].iloc[0]
                if "Gross Profit" in financials.index
                else np.nan
            )

            ev_gp = (
                ev / gross_profit
                if pd.notna(ev)
                and pd.notna(gross_profit)
                and gross_profit != 0
                else np.nan
            )

            value_df.loc[len(value_df)] = [
                ticker,
                price,
                pe_ratio,
                pb_ratio,
                ps_ratio,
                ev_ebitda,
                ev_gp
            ]

        except Exception as e:
            print(f"{ticker}: {e}")

    return value_df


tickers_list = tickers["Ticker"].tolist()

df = fetch_values_of_stocks(tickers_list)
df

$TATAMOTORS.NS: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")

TATAMOTORS.NS: no price data

,Ticker,Price,PE-Ratio,PB-Ratio,PS-Ratio,EV/EBITDA-Ratio,EV/GP
0,RELIANCE.NS,1320.000000,18.365366,1.976063,1.689609,12.303381,7.801917
1,TCS.NS,2297.399902,13.887369,7.322927,3.112936,11.163489,6.550987
2,HDFCBANK.NS,742.700012,11.819427,1.950839,4.036405,NaN,NaN
3,INFY.NS,1202.500000,14.670311,5.171048,241.460980,1060.390298,772.398176
4,ICICIBANK.NS,1239.699951,13.629969,2.445235,4.087273,NaN,NaN
5,HINDUNILVR.NS,2084.300049,38.900864,10.051165,7.596409,33.014487,15.589775
6,SBIN.NS,954.099976,9.346737,1.487618,2.338051,NaN,NaN
7,BAJFINANCE.NS,889.049988,17.980310,4.848341,12.611055,NaN,NaN
8,BHARTIARTL.NS,1810.599976,21.700672,7.101227,5.227792,10.591091,8.432559
9,ITC.NS,279.649994,15.737844,4.832717,4.442674,12.390982,7.412521
10,KOTAKBANK.NS,377.399994,13.478571,2.072226,5.069728,NaN,NaN
11,ADANIENT.NS,2909.399902,51.325745,4.647374,3.970021,36.155463,12.051830
12,LT.NS,4010.800049,21.865173,5.048397,1.892040,18.542598,6.897612
13,HCLTECH.NS,1195.099976,14.919844,4.213441,220.507740,1104.359804,5.994221
14,ASIANPAINT.NS,2632.399902,45.910637,12.882450,7.091861,37.822773,16.323877
15,AXISBANK.NS,1275.900024,10.126191,1.843472,5.324702,NaN,NaN
16,SUNPHARMA.NS,1796.500000,27.726913,5.536858,7.372999,24.530123,8.666722
17,WIPRO.NS,206.410004,14.344048,2.410994,2.337749,10.218630,6.604716
18,ULTRACEMCO.NS,11232.000000,25.657253,4.586570,3.732975,NaN,NaN
19,HDFCLIFE.NS,586.549988,47.842575,7.116857,1.267266,60.809330,NaN
20,ONGC.NS,264.299988,6.076362,0.894416,0.502073,4.570620,2.295752
21,NTPC.NS,378.700012,13.385381,1.808121,1.959674,8.807204,5.462206
22,POWERGRID.NS,286.149994,14.365738,2.647306,5.694852,10.866446,NaN
23,INDUSINDBK.NS,901.150024,12.443338,1.067470,4.072052,NaN,NaN
24,ADANIGREEN.NS,1446.900024,46.921745,12.780334,18.342947,32.633612,28.838820
25,TITAN.NS,4024.600098,46.883053,22.753923,4.076089,46.466200,59.818971
26,DIVISLAB.NS,6553.500000,46.350800,11.280622,16.474890,50.407838,26.821304
27,TECHM.NS,1543.199951,18.082548,4.971938,2.405758,13.921227,6.214675
28,MARUTI.NS,12946.000000,20.729270,3.798411,2.220349,18.431550,8.228129
29,COALINDIA.NS,472.600006,8.264050,2.445157,1.729513,5.852703,1.610033
30,BPCL.NS,296.850006,7.483515,1.266571,0.278611,3.772898,2.370917
31,JSWSTEEL.NS,1299.400024,17.895360,3.169810,1.709904,12.580086,4.779477
32,DRREDDY.NS,1290.400024,20.003254,2.849672,3.198198,15.823186,5.049776
33,BAJAJFINSV.NS,1758.900024,19.111473,3.604392,1.884030,12.182448,NaN
34,ADANIPORTS.NS,1783.500000,23.004000,4.274406,10.608052,21.160117,24.193362
35,CIPLA.NS,1390.300049,22.002989,3.411520,4.052749,17.455988,5.694419
36,BRITANNIA.NS,5157.500000,39.683647,24.329092,6.486554,35.206980,16.153185
37,HAVELLS.NS,1143.199951,33.611490,7.583768,3.183093,33.854783,10.800324
38,SHREECEM.NS,25060.000000,35.364582,9.812886,10.188592,31.881180,6.460780
39,GRASIM.NS,3102.600098,21.129490,2.112519,1.199390,13.281228,6.078369
40,TATASTEEL.NS,210.570007,11.200533,2.762624,1.131299,9.985439,2.509766
41,HEROMOTOCO.NS,4819.899902,15.117081,4.461784,2.034176,12.220326,5.472572
42,M&M.NS,2970.199951,18.552288,3.565161,1.764859,10.751194,5.888527
43,EICHERMOT.NS,7100.500000,26.779573,7.759855,8.326668,33.063048,19.301127
44,IOC.NS,138.800003,7.897968,0.870645,0.249871,4.144500,2.403871
45,SBICARD.NS,615.950012,16.994871,3.729008,4.939833,NaN,NaN
46,PIDILITIND.NS,1457.199951,48.055595,15.527235,10.157658,41.878742,18.167566
47,DMART.NS,4071.800049,57.423670,10.830753,3.858547,51.277616,25.668923
48,HDFCAMC.NS,2604.699951,29.679087,12.086551,24.155447,30.160250,31.518008

In [20]:
value_cols = [
        "PE-Ratio",
        "PB-Ratio",
        "PS-Ratio",
        "EV/EBITDA-Ratio",
        "EV/GP"
    ]
for col in value_cols:
    df[col] = df[col].fillna(df[col].mean())

df.info()

<class 'pandas.DataFrame'>
Index: 49 entries, 0 to 48
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Ticker           49 non-null     str
 1   Price            49 non-null     float64
 2   PE-Ratio         49 non-null     float64
 3   PB-Ratio         49 non-null     float64
 4   PS-Ratio         49 non-null     float64
 5   EV/EBITDA-Ratio  49 non-null     float64
 6   EV/GP            49 non-null     float64
dtypes: float64(6), str(1)
memory usage: 3.1 KB

In [22]:
percentile_metrics={
    "PE-Ratio": "PE-Ratio_Percentile",
    "PB-Ratio": "PB-Ratio_Percentile",
    "PS-Ratio": "PS-Ratio_Percentile",
    "EV/EBITDA-Ratio": "EV/EBITDA-Ratio_Percentile",
    "EV/GP": "EV/GP_Percentile"
}

for metric,percentile in percentile_metrics.items():
    df[percentile] = df[metric].apply(lambda x: stats.percentileofscore(df[metric], x)/100)
df.head()

,Ticker,Price,PE-Ratio,PB-Ratio,PS-Ratio,EV/EBITDA-Ratio,EV/GP,PE-Ratio_Percentile,PB-Ratio_Percentile,PS-Ratio_Percentile,EV/EBITDA-Ratio_Percentile,EV/GP_Percentile
0,RELIANCE.NS,1320.000000,18.365366,1.976063,1.689609,12.303381,7.801917,0.489796,0.183673,0.142857,0.285714,0.408163
1,TCS.NS,2297.399902,13.887369,7.322927,3.112936,11.163489,6.550987,0.265306,0.755102,0.387755,0.224490,0.326531
2,HDFCBANK.NS,742.700012,11.819427,1.950839,4.036405,75.373246,32.608805,0.163265,0.163265,0.510204,0.877551,0.846939
3,INFY.NS,1202.500000,14.670311,5.171048,241.460980,1060.390298,772.398176,0.326531,0.673469,1.000000,0.979592,1.000000
4,ICICIBANK.NS,1239.699951,13.629969,2.445235,4.087273,75.373246,32.608805,0.244898,0.285714,0.591837,0.877551,0.846939

In [23]:
from statistics import mean

df["Value_Score"] = df[[value for value in percentile_metrics.values()]].mean(axis=1)

df

,Ticker,Price,PE-Ratio,PB-Ratio,PS-Ratio,EV/EBITDA-Ratio,EV/GP,PE-Ratio_Percentile,PB-Ratio_Percentile,PS-Ratio_Percentile,EV/EBITDA-Ratio_Percentile,EV/GP_Percentile,Value_Score
0,RELIANCE.NS,1320.000000,18.365366,1.976063,1.689609,12.303381,7.801917,0.489796,0.183673,0.142857,0.285714,0.408163,0.302041
1,TCS.NS,2297.399902,13.887369,7.322927,3.112936,11.163489,6.550987,0.265306,0.755102,0.387755,0.224490,0.326531,0.391837
2,HDFCBANK.NS,742.700012,11.819427,1.950839,4.036405,75.373246,32.608805,0.163265,0.163265,0.510204,0.877551,0.846939,0.512245
3,INFY.NS,1202.500000,14.670311,5.171048,241.460980,1060.390298,772.398176,0.326531,0.673469,1.000000,0.979592,1.000000,0.795918
4,ICICIBANK.NS,1239.699951,13.629969,2.445235,4.087273,75.373246,32.608805,0.244898,0.285714,0.591837,0.877551,0.846939,0.569388
5,HINDUNILVR.NS,2084.300049,38.900864,10.051165,7.596409,33.014487,15.589775,0.816327,0.836735,0.795918,0.571429,0.530612,0.710204
6,SBIN.NS,954.099976,9.346737,1.487618,2.338051,75.373246,32.608805,0.102041,0.102041,0.346939,0.877551,0.846939,0.455102
7,BAJFINANCE.NS,889.049988,17.980310,4.848341,12.611055,75.373246,32.608805,0.448980,0.612245,0.897959,0.877551,0.846939,0.736735
8,BHARTIARTL.NS,1810.599976,21.700672,7.101227,5.227792,10.591091,8.432559,0.612245,0.714286,0.673469,0.163265,0.448980,0.522449
9,ITC.NS,279.649994,15.737844,4.832717,4.442674,12.390982,7.412521,0.387755,0.591837,0.612245,0.306122,0.387755,0.457143
10,KOTAKBANK.NS,377.399994,13.478571,2.072226,5.069728,75.373246,32.608805,0.224490,0.204082,0.653061,0.877551,0.846939,0.561224
11,ADANIENT.NS,2909.399902,51.325745,4.647374,3.970021,36.155463,12.051830,0.979592,0.571429,0.489796,0.653061,0.510204,0.640816
12,LT.NS,4010.800049,21.865173,5.048397,1.892040,18.542598,6.897612,0.632653,0.653061,0.244898,0.448980,0.367347,0.469388
13,HCLTECH.NS,1195.099976,14.919844,4.213441,220.507740,1104.359804,5.994221,0.346939,0.489796,0.979592,1.000000,0.244898,0.612245
14,ASIANPAINT.NS,2632.399902,45.910637,12.882450,7.091861,37.822773,16.323877,0.857143,0.938776,0.755102,0.673469,0.571429,0.759184
15,AXISBANK.NS,1275.900024,10.126191,1.843472,5.324702,75.373246,32.608805,0.122449,0.142857,0.693878,0.877551,0.846939,0.536735
16,SUNPHARMA.NS,1796.500000,27.726913,5.536858,7.372999,24.530123,8.666722,0.734694,0.693878,0.775510,0.489796,0.469388,0.632653
17,WIPRO.NS,206.410004,14.344048,2.410994,2.337749,10.218630,6.604716,0.285714,0.244898,0.326531,0.142857,0.346939,0.269388
18,ULTRACEMCO.NS,11232.000000,25.657253,4.586570,3.732975,75.373246,32.608805,0.693878,0.551020,0.448980,0.877551,0.846939,0.683673
19,HDFCLIFE.NS,586.549988,47.842575,7.116857,1.267266,60.809330,32.608805,0.938776,0.734694,0.122449,0.775510,0.846939,0.683673
20,ONGC.NS,264.299988,6.076362,0.894416,0.502073,4.570620,2.295752,0.020408,0.040816,0.061224,0.061224,0.040816,0.044898
21,NTPC.NS,378.700012,13.385381,1.808121,1.959674,8.807204,5.462206,0.204082,0.122449,0.265306,0.102041,0.163265,0.171429
22,POWERGRID.NS,286.149994,14.365738,2.647306,5.694852,10.866446,32.608805,0.306122,0.306122,0.714286,0.204082,0.846939,0.475510
23,INDUSINDBK.NS,901.150024,12.443338,1.067470,4.072052,75.373246,32.608805,0.183673,0.061224,0.551020,0.877551,0.846939,0.504082
24,ADANIGREEN.NS,1446.900024,46.921745,12.780334,18.342947,32.633612,28.838820,0.918367,0.918367,0.938776,0.551020,0.693878,0.804082
25,TITAN.NS,4024.600098,46.883053,22.753923,4.076089,46.466200,59.818971,0.897959,0.979592,0.571429,0.714286,0.979592,0.828571
26,DIVISLAB.NS,6553.500000,46.350800,11.280622,16.474890,50.407838,26.821304,0.877551,0.877551,0.918367,0.734694,0.673469,0.816327
27,TECHM.NS,1543.199951,18.082548,4.971938,2.405758,13.921227,6.214675,0.469388,0.632653,0.367347,0.367347,0.285714,0.424490
28,MARUTI.NS,12946.000000,20.729270,3.798411,2.220349,18.431550,8.228129,0.571429,0.469388,0.306122,0.428571,0.428571,0.440816
29,COALINDIA.NS,472.600006,8.264050,2.445157,1.729513,5.852703,1.610033,0.081633,0.265306,0.183673,0.081633,0.020408,0.126531
30,BPCL.NS,296.850006,7.483515,1.266571,0.278611,3.772898,2.370917,0.040816,0.081633,0.040816,0.020408,0.061224,0.048980
31,JSWSTEEL.NS,1299.400024,17.895360,3.169810,1.709904,12.580086,4.779477,0.428571,0.367347,0.163265,0.326531,0.122449,0.281633
32,DRREDDY.NS,1290.400024,20.003254,2.849672,3.198198,15.823186,5.049776,0.551020,0.346939,0.428571,0.387755,0.142857,0.371429
33,BAJAJFINSV.NS,1758.900024,19.111473,3.604392,1.884030,12.182448,32.608805,0.530612,0.428571,0.224490,0.244898,0.846939,0.455102
34,ADANIPORTS.NS,1783.500000,23.004000,4.274406,10.608052,21.160117,24.193362,0.673469,0.510204,0.877551,0.469388,0.632653,0.632653
35,CIPLA.NS,1390.300049,22.002989,3.411520,4.052749,17.455988,5.694419,0.653061,0.387755,0.530612,0.408163,0.204082,0.436735
36,BRITANNIA.NS,5157.500000,39.683647,24.329092,6.486554,35.206980,16.153185,0.836735,1.000000,0.734694,0.632653,0.551020,0.751020
37,HAVELLS.NS,1143.199951,33.611490,7.583768,3.183093,33.854783,10.800324,0.775510,0.775510,0.408163,0.612245,0.489796,0.612245
38,SHREECEM.NS,25060.000000,35.364582,9.812886,10.188592,31.881180,6.460780,0.795918,0.816327,0.857143,0.530612,0.306122,0.661224
39,GRASIM.NS,3102.600098,21.129490,2.112519,1.199390,13.281228,6.078369,0.591837,0.224490,0.102041,0.346939,0.265306,0.306122
40,TATASTEEL.NS,210.570007,11.200533,2.762624,1.131299,9.985439,2.509766,0.142857,0.326531,0.081633,0.122449,0.102041,0.155102
41,HEROMOTOCO.NS,4819.899902,15.117081,4.461784,2.034176,12.220326,5.472572,0.367347,0.530612,0.285714,0.265306,0.183673,0.326531
42,M&M.NS,2970.199951,18.552288,3.565161,1.764859,10.751194,5.888527,0.510204,0.408163,0.204082,0.183673,0.224490,0.306122
43,EICHERMOT.NS,7100.500000,26.779573,7.759855,8.326668,33.063048,19.301127,0.714286,0.795918,0.816327,0.591837,0.612245,0.706122
44,IOC.NS,138.800003,7.897968,0.870645,0.249871,4.144500,2.403871,0.061224,0.020408,0.020408,0.040816,0.081633,0.044898
45,SBICARD.NS,615.950012,16.994871,3.729008,4.939833,75.373246,32.608805,0.408163,0.448980,0.632653,0.877551,0.846939,0.642857
46,PIDILITIND.NS,1457.199951,48.055595,15.527235,10.157658,41.878742,18.167566,0.959184,0.959184,0.836735,0.693878,0.591837,0.808163
47,DMART.NS,4071.800049,57.423670,10.830753,3.858547,51.277616,25.668923,1.000000,0.857143,0.469388,0.755102,0.653061,0.746939
48,HDFCAMC.NS,2604.699951,29.679087,12.086551,24.155447,30.160250,31.518008,0.755102,0.897959,0.959184,0.510204,0.714286,0.767347

In [24]:
df=df.sort_values(by="Value_Score", ascending=False).reset_index(drop=True)
df

,Ticker,Price,PE-Ratio,PB-Ratio,PS-Ratio,EV/EBITDA-Ratio,EV/GP,PE-Ratio_Percentile,PB-Ratio_Percentile,PS-Ratio_Percentile,EV/EBITDA-Ratio_Percentile,EV/GP_Percentile,Value_Score
0,TITAN.NS,4024.600098,46.883053,22.753923,4.076089,46.466200,59.818971,0.897959,0.979592,0.571429,0.714286,0.979592,0.828571
1,DIVISLAB.NS,6553.500000,46.350800,11.280622,16.474890,50.407838,26.821304,0.877551,0.877551,0.918367,0.734694,0.673469,0.816327
2,PIDILITIND.NS,1457.199951,48.055595,15.527235,10.157658,41.878742,18.167566,0.959184,0.959184,0.836735,0.693878,0.591837,0.808163
3,ADANIGREEN.NS,1446.900024,46.921745,12.780334,18.342947,32.633612,28.838820,0.918367,0.918367,0.938776,0.551020,0.693878,0.804082
4,INFY.NS,1202.500000,14.670311,5.171048,241.460980,1060.390298,772.398176,0.326531,0.673469,1.000000,0.979592,1.000000,0.795918
5,HDFCAMC.NS,2604.699951,29.679087,12.086551,24.155447,30.160250,31.518008,0.755102,0.897959,0.959184,0.510204,0.714286,0.767347
6,ASIANPAINT.NS,2632.399902,45.910637,12.882450,7.091861,37.822773,16.323877,0.857143,0.938776,0.755102,0.673469,0.571429,0.759184
7,BRITANNIA.NS,5157.500000,39.683647,24.329092,6.486554,35.206980,16.153185,0.836735,1.000000,0.734694,0.632653,0.551020,0.751020
8,DMART.NS,4071.800049,57.423670,10.830753,3.858547,51.277616,25.668923,1.000000,0.857143,0.469388,0.755102,0.653061,0.746939
9,BAJFINANCE.NS,889.049988,17.980310,4.848341,12.611055,75.373246,32.608805,0.448980,0.612245,0.897959,0.877551,0.846939,0.736735
10,HINDUNILVR.NS,2084.300049,38.900864,10.051165,7.596409,33.014487,15.589775,0.816327,0.836735,0.795918,0.571429,0.530612,0.710204
11,EICHERMOT.NS,7100.500000,26.779573,7.759855,8.326668,33.063048,19.301127,0.714286,0.795918,0.816327,0.591837,0.612245,0.706122
12,HDFCLIFE.NS,586.549988,47.842575,7.116857,1.267266,60.809330,32.608805,0.938776,0.734694,0.122449,0.775510,0.846939,0.683673
13,ULTRACEMCO.NS,11232.000000,25.657253,4.586570,3.732975,75.373246,32.608805,0.693878,0.551020,0.448980,0.877551,0.846939,0.683673
14,SHREECEM.NS,25060.000000,35.364582,9.812886,10.188592,31.881180,6.460780,0.795918,0.816327,0.857143,0.530612,0.306122,0.661224
15,SBICARD.NS,615.950012,16.994871,3.729008,4.939833,75.373246,32.608805,0.408163,0.448980,0.632653,0.877551,0.846939,0.642857
16,ADANIENT.NS,2909.399902,51.325745,4.647374,3.970021,36.155463,12.051830,0.979592,0.571429,0.489796,0.653061,0.510204,0.640816
17,ADANIPORTS.NS,1783.500000,23.004000,4.274406,10.608052,21.160117,24.193362,0.673469,0.510204,0.877551,0.469388,0.632653,0.632653
18,SUNPHARMA.NS,1796.500000,27.726913,5.536858,7.372999,24.530123,8.666722,0.734694,0.693878,0.775510,0.489796,0.469388,0.632653
19,HCLTECH.NS,1195.099976,14.919844,4.213441,220.507740,1104.359804,5.994221,0.346939,0.489796,0.979592,1.000000,0.244898,0.612245
20,HAVELLS.NS,1143.199951,33.611490,7.583768,3.183093,33.854783,10.800324,0.775510,0.775510,0.408163,0.612245,0.489796,0.612245
21,ICICIBANK.NS,1239.699951,13.629969,2.445235,4.087273,75.373246,32.608805,0.244898,0.285714,0.591837,0.877551,0.846939,0.569388
22,KOTAKBANK.NS,377.399994,13.478571,2.072226,5.069728,75.373246,32.608805,0.224490,0.204082,0.653061,0.877551,0.846939,0.561224
23,AXISBANK.NS,1275.900024,10.126191,1.843472,5.324702,75.373246,32.608805,0.122449,0.142857,0.693878,0.877551,0.846939,0.536735
24,BHARTIARTL.NS,1810.599976,21.700672,7.101227,5.227792,10.591091,8.432559,0.612245,0.714286,0.673469,0.163265,0.448980,0.522449
25,HDFCBANK.NS,742.700012,11.819427,1.950839,4.036405,75.373246,32.608805,0.163265,0.163265,0.510204,0.877551,0.846939,0.512245
26,INDUSINDBK.NS,901.150024,12.443338,1.067470,4.072052,75.373246,32.608805,0.183673,0.061224,0.551020,0.877551,0.846939,0.504082
27,POWERGRID.NS,286.149994,14.365738,2.647306,5.694852,10.866446,32.608805,0.306122,0.306122,0.714286,0.204082,0.846939,0.475510
28,LT.NS,4010.800049,21.865173,5.048397,1.892040,18.542598,6.897612,0.632653,0.653061,0.244898,0.448980,0.367347,0.469388
29,ITC.NS,279.649994,15.737844,4.832717,4.442674,12.390982,7.412521,0.387755,0.591837,0.612245,0.306122,0.387755,0.457143
30,BAJAJFINSV.NS,1758.900024,19.111473,3.604392,1.884030,12.182448,32.608805,0.530612,0.428571,0.224490,0.244898,0.846939,0.455102
31,SBIN.NS,954.099976,9.346737,1.487618,2.338051,75.373246,32.608805,0.102041,0.102041,0.346939,0.877551,0.846939,0.455102
32,MARUTI.NS,12946.000000,20.729270,3.798411,2.220349,18.431550,8.228129,0.571429,0.469388,0.306122,0.428571,0.428571,0.440816
33,CIPLA.NS,1390.300049,22.002989,3.411520,4.052749,17.455988,5.694419,0.653061,0.387755,0.530612,0.408163,0.204082,0.436735
34,TECHM.NS,1543.199951,18.082548,4.971938,2.405758,13.921227,6.214675,0.469388,0.632653,0.367347,0.367347,0.285714,0.424490
35,TCS.NS,2297.399902,13.887369,7.322927,3.112936,11.163489,6.550987,0.265306,0.755102,0.387755,0.224490,0.326531,0.391837
36,DRREDDY.NS,1290.400024,20.003254,2.849672,3.198198,15.823186,5.049776,0.551020,0.346939,0.428571,0.387755,0.142857,0.371429
37,HEROMOTOCO.NS,4819.899902,15.117081,4.461784,2.034176,12.220326,5.472572,0.367347,0.530612,0.285714,0.265306,0.183673,0.326531
38,M&M.NS,2970.199951,18.552288,3.565161,1.764859,10.751194,5.888527,0.510204,0.408163,0.204082,0.183673,0.224490,0.306122
39,GRASIM.NS,3102.600098,21.129490,2.112519,1.199390,13.281228,6.078369,0.591837,0.224490,0.102041,0.346939,0.265306,0.306122
40,RELIANCE.NS,1320.000000,18.365366,1.976063,1.689609,12.303381,7.801917,0.489796,0.183673,0.142857,0.285714,0.408163,0.302041
41,JSWSTEEL.NS,1299.400024,17.895360,3.169810,1.709904,12.580086,4.779477,0.428571,0.367347,0.163265,0.326531,0.122449,0.281633
42,WIPRO.NS,206.410004,14.344048,2.410994,2.337749,10.218630,6.604716,0.285714,0.244898,0.326531,0.142857,0.346939,0.269388
43,NTPC.NS,378.700012,13.385381,1.808121,1.959674,8.807204,5.462206,0.204082,0.122449,0.265306,0.102041,0.163265,0.171429
44,TATASTEEL.NS,210.570007,11.200533,2.762624,1.131299,9.985439,2.509766,0.142857,0.326531,0.081633,0.122449,0.102041,0.155102
45,COALINDIA.NS,472.600006,8.264050,2.445157,1.729513,5.852703,1.610033,0.081633,0.265306,0.183673,0.081633,0.020408,0.126531
46,BPCL.NS,296.850006,7.483515,1.266571,0.278611,3.772898,2.370917,0.040816,0.081633,0.040816,0.020408,0.061224,0.048980
47,ONGC.NS,264.299988,6.076362,0.894416,0.502073,4.570620,2.295752,0.020408,0.040816,0.061224,0.061224,0.040816,0.044898
48,IOC.NS,138.800003,7.897968,0.870645,0.249871,4.144500,2.403871,0.061224,0.020408,0.020408,0.040816,0.081633,0.044898

In [25]:
df.head(10)

,Ticker,Price,PE-Ratio,PB-Ratio,PS-Ratio,EV/EBITDA-Ratio,EV/GP,PE-Ratio_Percentile,PB-Ratio_Percentile,PS-Ratio_Percentile,EV/EBITDA-Ratio_Percentile,EV/GP_Percentile,Value_Score
0,TITAN.NS,4024.600098,46.883053,22.753923,4.076089,46.466200,59.818971,0.897959,0.979592,0.571429,0.714286,0.979592,0.828571
1,DIVISLAB.NS,6553.500000,46.350800,11.280622,16.474890,50.407838,26.821304,0.877551,0.877551,0.918367,0.734694,0.673469,0.816327
2,PIDILITIND.NS,1457.199951,48.055595,15.527235,10.157658,41.878742,18.167566,0.959184,0.959184,0.836735,0.693878,0.591837,0.808163
3,ADANIGREEN.NS,1446.900024,46.921745,12.780334,18.342947,32.633612,28.838820,0.918367,0.918367,0.938776,0.551020,0.693878,0.804082
4,INFY.NS,1202.500000,14.670311,5.171048,241.460980,1060.390298,772.398176,0.326531,0.673469,1.000000,0.979592,1.000000,0.795918
5,HDFCAMC.NS,2604.699951,29.679087,12.086551,24.155447,30.160250,31.518008,0.755102,0.897959,0.959184,0.510204,0.714286,0.767347
6,ASIANPAINT.NS,2632.399902,45.910637,12.882450,7.091861,37.822773,16.323877,0.857143,0.938776,0.755102,0.673469,0.571429,0.759184
7,BRITANNIA.NS,5157.500000,39.683647,24.329092,6.486554,35.206980,16.153185,0.836735,1.000000,0.734694,0.632653,0.551020,0.751020
8,DMART.NS,4071.800049,57.423670,10.830753,3.858547,51.277616,25.668923,1.000000,0.857143,0.469388,0.755102,0.653061,0.746939
9,BAJFINANCE.NS,889.049988,17.980310,4.848341,12.611055,75.373246,32.608805,0.448980,0.612245,0.897959,0.877551,0.846939,0.736735