## Divident based investing

In [1]:
import pandas as pd 
import numpy as np 
import yfinance as yf 
import math
from scipy import stats

In [2]:
tickers= pd.read_csv('top_50_indian_stocks.csv')
tickers.head()

         Ticker               Company Name
0   RELIANCE.NS        Reliance Industries
1        TCS.NS  Tata Consultancy Services
2   HDFCBANK.NS                  HDFC Bank
3       INFY.NS                    Infosys
4  ICICIBANK.NS                 ICICI Bank

## Weighted scoring model for finding the final score

In [10]:
import pandas as pd
import numpy as np
import yfinance as yf

def create_dividend_df(tickers):

    columns = [
        "Ticker",
        "Dividend_Yield(%)",
        "Dividend Rate",
        "Payout Ratio(%)",
        "5 Year Dividend Growth Rate(%)",
        "Earning Growth(%)"
    ]

    dividend_df = pd.DataFrame(columns=columns)

    for stock in tickers:
        ticker = yf.Ticker(stock)
        info = ticker.info

        divident_yield = (
            info.get("dividendYield", np.nan) * 100
            if info.get("dividendYield") is not None
            else np.nan
        )

        divident_rate = (
            info.get("dividendRate", np.nan)
            if info.get("dividendRate") is not None
            else np.nan
        )

        payout_ratio = (
            info.get("payoutRatio", np.nan) * 100
            if info.get("payoutRatio") is not None
            else np.nan
        )

        five_year_dividend_growth_rate = (
            info.get("fiveYearAvgDividendYield", np.nan) * 100
            if info.get("fiveYearAvgDividendYield") is not None
            else np.nan
        )

        earning_growth = (
            info.get("earningsGrowth", np.nan) * 100
            if info.get("earningsGrowth") is not None
            else np.nan
        )

        dividend_df.loc[len(dividend_df)] = [
            stock,
            divident_yield,
            divident_rate,
            payout_ratio,
            five_year_dividend_growth_rate,
            earning_growth
        ]

    numeric_cols = [
        "Dividend_Yield(%)",
        "Dividend Rate",
        "Payout Ratio(%)",
        "5 Year Dividend Growth Rate(%)",
        "Earning Growth(%)"
    ]

    for col in numeric_cols:

        if col == "Payout Ratio(%)":
            dividend_df[col + "_Normalized"] = 1 - (
                (dividend_df[col] - dividend_df[col].min()) /
                (dividend_df[col].max() - dividend_df[col].min())
            )

        else:
            dividend_df[col + "_Normalized"] = (
                (dividend_df[col] - dividend_df[col].min()) /
                (dividend_df[col].max() - dividend_df[col].min())
            )

    return dividend_df

In [11]:
tickers_list = tickers["Ticker"].tolist()
dividend_df = create_dividend_df(tickers_list)
dividend_df

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TATAMOTORS.NS"}}}

,Ticker,Dividend_Yield(%),Dividend Rate,Payout Ratio(%),5 Year Dividend Growth Rate(%),Earning Growth(%),Dividend_Yield(%)_Normalized,Dividend Rate_Normalized,Payout Ratio(%)_Normalized,5 Year Dividend Growth Rate(%)_Normalized,Earning Growth(%)_Normalized
0,RELIANCE.NS,45.0,6.0,9.21,44.0,-12.6,0.049517,0.02981,0.903083,0.047146,0.068275
1,TCS.NS,549.0,124.0,46.32,149.0,12.2,0.658213,0.669377,0.512575,0.177419,0.09128
2,HDFCBANK.NS,175.0,13.0,21.76,102.0,7.5,0.206522,0.067751,0.77102,0.119107,0.08692
3,INFY.NS,431.0,50.0,64.65,240.0,11.8,0.5157,0.268293,0.319689,0.290323,0.090909
4,ICICIBANK.NS,88.0,11.0,14.71,99.0,8.4,0.101449,0.056911,0.845207,0.115385,0.087755
5,HINDUNILVR.NS,204.0,44.0,95.03,158.0,21.4,0.241546,0.235772,0.0,0.188586,0.099814
6,SBIN.NS,180.0,17.35,17.44,150.0,-3.1,0.21256,0.091328,0.816479,0.17866,0.077087
7,BAJFINANCE.NS,59.0,5.4,14.42,24.0,21.4,0.066425,0.026558,0.848258,0.022333,0.099814
8,BHARTIARTL.NS,87.0,16.0,36.060002,80.0,-34.0,0.100242,0.084011,0.620541,0.091811,0.048423
9,ITC.NS,558.0,16.0,86.92,372.0,-72.7,0.669082,0.084011,0.085341,0.454094,0.012523
10,KOTAKBANK.NS,13.0,0.5,2.58,6.0,9.8,0.01087,0.0,0.972851,0.0,0.089054
11,ADANIENT.NS,4.0,1.3,1.71,65.0,NaN,0.0,0.004336,0.982006,0.073201,NaN
12,LT.NS,93.0,38.0,29.09,91.0,-34.5,0.107488,0.203252,0.693886,0.105459,0.047959
13,HCLTECH.NS,811.0,96.0,88.01,357.0,-0.2,0.974638,0.517615,0.073871,0.435484,0.079777
14,ASIANPAINT.NS,103.0,27.5,55.53,87.0,69.3,0.119565,0.146341,0.415658,0.100496,0.144249
15,AXISBANK.NS,8.0,1.0,1.18,103.0,6.4,0.004831,0.00271,0.987583,0.120347,0.0859
16,SUNPHARMA.NS,92.0,16.5,34.52,93.0,25.6,0.10628,0.086721,0.636746,0.10794,0.103711
17,WIPRO.NS,832.0,17.0,87.58,151.0,-1.6,1.0,0.089431,0.078396,0.179901,0.078479
18,ULTRACEMCO.NS,67.0,77.5,27.93,53.0,NaN,0.076087,0.417344,0.706093,0.058313,NaN
19,HDFCLIFE.NS,35.0,2.1,23.7,31.0,4.1,0.03744,0.008672,0.750605,0.031017,0.083766
20,ONGC.NS,697.0,18.5,41.0,511.0,47.8,0.836957,0.097561,0.568557,0.626551,0.124304
21,NTPC.NS,293.0,11.35,29.07,336.0,-1.6,0.349034,0.058808,0.694097,0.409429,0.078479
22,POWERGRID.NS,422.0,12.25,44.75,474.0,9.6,0.504831,0.063686,0.529096,0.580645,0.088868
23,TATAMOTORS.NS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,INDUSINDBK.NS,16.0,1.5,0.0,54.0,NaN,0.014493,0.00542,1.0,0.059553,NaN
25,ADANIGREEN.NS,NaN,NaN,0.0,NaN,209.8,NaN,NaN,1.0,NaN,0.274583
26,TITAN.NS,27.0,11.0,19.229999,27.0,35.1,0.027778,0.056911,0.797643,0.026055,0.112523
27,DIVISLAB.NS,45.0,30.0,31.01,114.0,13.6,0.049517,0.159892,0.673682,0.133995,0.092579
28,TECHM.NS,344.0,51.0,83.04,232.0,15.9,0.410628,0.273713,0.126171,0.280397,0.094712
29,MARUTI.NS,107.0,140.0,28.91,80.0,-6.4,0.124396,0.756098,0.69578,0.091811,0.074026
30,COALINDIA.NS,480.0,22.0,52.32,812.0,12.9,0.574879,0.116531,0.449437,1.0,0.091929
31,BPCL.NS,671.0,20.0,37.2,540.0,28.0,0.805556,0.105691,0.608545,0.662531,0.105937
32,JSWSTEEL.NS,56.0,7.1,3.07,98.0,991.8,0.062802,0.035772,0.967694,0.114144,1.0
33,DRREDDY.NS,61.0,8.0,15.890001,63.0,-86.2,0.068841,0.04065,0.83279,0.07072,0.0
34,BAJAJFINSV.NS,7.0,1.3,1.64,14.0,5.7,0.003623,0.004336,0.982742,0.009926,0.08525
35,ADANIPORTS.NS,42.0,7.5,12.020001,57.0,3.6,0.045894,0.03794,0.873514,0.063275,0.083302
36,CIPLA.NS,93.0,13.0,27.08,48.0,-54.6,0.107488,0.067751,0.715037,0.052109,0.029314
37,BRITANNIA.NS,174.0,90.5,71.309996,172.0,21.1,0.205314,0.487805,0.249605,0.205955,0.099536
38,HAVELLS.NS,102.0,12.0,37.12,59.0,39.6,0.118357,0.062331,0.609387,0.065757,0.116698
39,SHREECEM.NS,63.0,160.0,28.97,33.0,3.4,0.071256,0.864499,0.695149,0.033499,0.083117
40,GRASIM.NS,32.0,10.0,13.67,36.0,60.8,0.033816,0.051491,0.856151,0.037221,0.136364
41,TATASTEEL.NS,192.0,4.0,48.98,280.0,125.4,0.227053,0.01897,0.484584,0.33995,0.196289
42,HEROMOTOCO.NS,377.0,185.0,61.04,313.0,25.7,0.450483,1.0,0.357677,0.380893,0.103803
43,M&M.NS,108.0,33.0,16.63,86.0,44.8,0.125604,0.176152,0.825003,0.099256,0.121521
44,EICHERMOT.NS,98.0,70.0,34.87,45.0,11.5,0.113527,0.376694,0.633063,0.048387,0.090631
45,IOC.NS,713.0,10.0,32.709998,669.0,78.1,0.85628,0.051491,0.655793,0.822581,0.152412
46,SBICARD.NS,40.0,2.5,10.98,NaN,13.9,0.043478,0.01084,0.884458,NaN,0.092857
47,PIDILITIND.NS,67.0,10.0,41.65,51.0,37.0,0.076087,0.051491,0.561717,0.055831,0.114286
48,DMART.NS,NaN,NaN,0.0,NaN,19.6,NaN,NaN,1.0,NaN,0.098145
49,HDFCAMC.NS,202.0,54.0,67.67,171.0,-2.8,0.23913,0.289973,0.287909,0.204715,0.077365

In [12]:
weights={
    "Dividend_Yield(%)_Normalized": 0.3,
    "Dividend Rate_Normalized": 0.2,
    "Payout Ratio(%)_Normalized": 0.2,
    "5 Year Dividend Growth Rate(%)_Normalized": 0.2,
    "Earning Growth(%)_Normalized": 0.1
}

dividend_df["Dividend_Score"] = dividend_df[[col for col in weights.keys()]].mul(list(weights.values())).sum(axis=1)
dividend_df

,Ticker,Dividend_Yield(%),Dividend Rate,Payout Ratio(%),5 Year Dividend Growth Rate(%),Earning Growth(%),Dividend_Yield(%)_Normalized,Dividend Rate_Normalized,Payout Ratio(%)_Normalized,5 Year Dividend Growth Rate(%)_Normalized,Earning Growth(%)_Normalized,Dividend_Score
0,RELIANCE.NS,45.0,6.0,9.21,44.0,-12.6,0.049517,0.02981,0.903083,0.047146,0.068275,0.217691
1,TCS.NS,549.0,124.0,46.32,149.0,12.2,0.658213,0.669377,0.512575,0.177419,0.09128,0.478466
2,HDFCBANK.NS,175.0,13.0,21.76,102.0,7.5,0.206522,0.067751,0.77102,0.119107,0.08692,0.262224
3,INFY.NS,431.0,50.0,64.65,240.0,11.8,0.5157,0.268293,0.319689,0.290323,0.090909,0.339462
4,ICICIBANK.NS,88.0,11.0,14.71,99.0,8.4,0.101449,0.056911,0.845207,0.115385,0.087755,0.242711
5,HINDUNILVR.NS,204.0,44.0,95.03,158.0,21.4,0.241546,0.235772,0.0,0.188586,0.099814,0.167317
6,SBIN.NS,180.0,17.35,17.44,150.0,-3.1,0.21256,0.091328,0.816479,0.17866,0.077087,0.28877
7,BAJFINANCE.NS,59.0,5.4,14.42,24.0,21.4,0.066425,0.026558,0.848258,0.022333,0.099814,0.209339
8,BHARTIARTL.NS,87.0,16.0,36.060002,80.0,-34.0,0.100242,0.084011,0.620541,0.091811,0.048423,0.194187
9,ITC.NS,558.0,16.0,86.92,372.0,-72.7,0.669082,0.084011,0.085341,0.454094,0.012523,0.326666
10,KOTAKBANK.NS,13.0,0.5,2.58,6.0,9.8,0.01087,0.0,0.972851,0.0,0.089054,0.206736
11,ADANIENT.NS,4.0,1.3,1.71,65.0,NaN,0.0,0.004336,0.982006,0.073201,NaN,0.211909
12,LT.NS,93.0,38.0,29.09,91.0,-34.5,0.107488,0.203252,0.693886,0.105459,0.047959,0.237562
13,HCLTECH.NS,811.0,96.0,88.01,357.0,-0.2,0.974638,0.517615,0.073871,0.435484,0.079777,0.505763
14,ASIANPAINT.NS,103.0,27.5,55.53,87.0,69.3,0.119565,0.146341,0.415658,0.100496,0.144249,0.182794
15,AXISBANK.NS,8.0,1.0,1.18,103.0,6.4,0.004831,0.00271,0.987583,0.120347,0.0859,0.232167
16,SUNPHARMA.NS,92.0,16.5,34.52,93.0,25.6,0.10628,0.086721,0.636746,0.10794,0.103711,0.208537
17,WIPRO.NS,832.0,17.0,87.58,151.0,-1.6,1.0,0.089431,0.078396,0.179901,0.078479,0.377393
18,ULTRACEMCO.NS,67.0,77.5,27.93,53.0,NaN,0.076087,0.417344,0.706093,0.058313,NaN,0.259176
19,HDFCLIFE.NS,35.0,2.1,23.7,31.0,4.1,0.03744,0.008672,0.750605,0.031017,0.083766,0.177667
20,ONGC.NS,697.0,18.5,41.0,511.0,47.8,0.836957,0.097561,0.568557,0.626551,0.124304,0.522051
21,NTPC.NS,293.0,11.35,29.07,336.0,-1.6,0.349034,0.058808,0.694097,0.409429,0.078479,0.345025
22,POWERGRID.NS,422.0,12.25,44.75,474.0,9.6,0.504831,0.063686,0.529096,0.580645,0.088868,0.395021
23,TATAMOTORS.NS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
24,INDUSINDBK.NS,16.0,1.5,0.0,54.0,NaN,0.014493,0.00542,1.0,0.059553,NaN,0.217343
25,ADANIGREEN.NS,NaN,NaN,0.0,NaN,209.8,NaN,NaN,1.0,NaN,0.274583,0.227458
26,TITAN.NS,27.0,11.0,19.229999,27.0,35.1,0.027778,0.056911,0.797643,0.026055,0.112523,0.195707
27,DIVISLAB.NS,45.0,30.0,31.01,114.0,13.6,0.049517,0.159892,0.673682,0.133995,0.092579,0.217627
28,TECHM.NS,344.0,51.0,83.04,232.0,15.9,0.410628,0.273713,0.126171,0.280397,0.094712,0.268716
29,MARUTI.NS,107.0,140.0,28.91,80.0,-6.4,0.124396,0.756098,0.69578,0.091811,0.074026,0.353459
30,COALINDIA.NS,480.0,22.0,52.32,812.0,12.9,0.574879,0.116531,0.449437,1.0,0.091929,0.49485
31,BPCL.NS,671.0,20.0,37.2,540.0,28.0,0.805556,0.105691,0.608545,0.662531,0.105937,0.527614
32,JSWSTEEL.NS,56.0,7.1,3.07,98.0,991.8,0.062802,0.035772,0.967694,0.114144,1.0,0.342363
33,DRREDDY.NS,61.0,8.0,15.890001,63.0,-86.2,0.068841,0.04065,0.83279,0.07072,0.0,0.209484
34,BAJAJFINSV.NS,7.0,1.3,1.64,14.0,5.7,0.003623,0.004336,0.982742,0.009926,0.08525,0.209013
35,ADANIPORTS.NS,42.0,7.5,12.020001,57.0,3.6,0.045894,0.03794,0.873514,0.063275,0.083302,0.217044
36,CIPLA.NS,93.0,13.0,27.08,48.0,-54.6,0.107488,0.067751,0.715037,0.052109,0.029314,0.202157
37,BRITANNIA.NS,174.0,90.5,71.309996,172.0,21.1,0.205314,0.487805,0.249605,0.205955,0.099536,0.260221
38,HAVELLS.NS,102.0,12.0,37.12,59.0,39.6,0.118357,0.062331,0.609387,0.065757,0.116698,0.194672
39,SHREECEM.NS,63.0,160.0,28.97,33.0,3.4,0.071256,0.864499,0.695149,0.033499,0.083117,0.348318
40,GRASIM.NS,32.0,10.0,13.67,36.0,60.8,0.033816,0.051491,0.856151,0.037221,0.136364,0.212754
41,TATASTEEL.NS,192.0,4.0,48.98,280.0,125.4,0.227053,0.01897,0.484584,0.33995,0.196289,0.256446
42,HEROMOTOCO.NS,377.0,185.0,61.04,313.0,25.7,0.450483,1.0,0.357677,0.380893,0.103803,0.493239
43,M&M.NS,108.0,33.0,16.63,86.0,44.8,0.125604,0.176152,0.825003,0.099256,0.121521,0.269915
44,EICHERMOT.NS,98.0,70.0,34.87,45.0,11.5,0.113527,0.376694,0.633063,0.048387,0.090631,0.25475
45,IOC.NS,713.0,10.0,32.709998,669.0,78.1,0.85628,0.051491,0.655793,0.822581,0.152412,0.578098
46,SBICARD.NS,40.0,2.5,10.98,NaN,13.9,0.043478,0.01084,0.884458,NaN,0.092857,0.201389
47,PIDILITIND.NS,67.0,10.0,41.65,51.0,37.0,0.076087,0.051491,0.561717,0.055831,0.114286,0.168062
48,DMART.NS,NaN,NaN,0.0,NaN,19.6,NaN,NaN,1.0,NaN,0.098145,0.209814
49,HDFCAMC.NS,202.0,54.0,67.67,171.0,-2.8,0.23913,0.289973,0.287909,0.204715,0.077365,0.235995

In [14]:
dividend_df = dividend_df.sort_values(by="Dividend_Score", ascending=False)
dividend_df.head(10)

,Ticker,Dividend_Yield(%),Dividend Rate,Payout Ratio(%),5 Year Dividend Growth Rate(%),Earning Growth(%),Dividend_Yield(%)_Normalized,Dividend Rate_Normalized,Payout Ratio(%)_Normalized,5 Year Dividend Growth Rate(%)_Normalized,Earning Growth(%)_Normalized,Dividend_Score
45,IOC.NS,713.0,10.0,32.709998,669.0,78.1,0.85628,0.051491,0.655793,0.822581,0.152412,0.578098
31,BPCL.NS,671.0,20.0,37.2,540.0,28.0,0.805556,0.105691,0.608545,0.662531,0.105937,0.527614
20,ONGC.NS,697.0,18.5,41.0,511.0,47.8,0.836957,0.097561,0.568557,0.626551,0.124304,0.522051
13,HCLTECH.NS,811.0,96.0,88.01,357.0,-0.2,0.974638,0.517615,0.073871,0.435484,0.079777,0.505763
30,COALINDIA.NS,480.0,22.0,52.32,812.0,12.9,0.574879,0.116531,0.449437,1.0,0.091929,0.49485
42,HEROMOTOCO.NS,377.0,185.0,61.04,313.0,25.7,0.450483,1.0,0.357677,0.380893,0.103803,0.493239
1,TCS.NS,549.0,124.0,46.32,149.0,12.2,0.658213,0.669377,0.512575,0.177419,0.09128,0.478466
22,POWERGRID.NS,422.0,12.25,44.75,474.0,9.6,0.504831,0.063686,0.529096,0.580645,0.088868,0.395021
17,WIPRO.NS,832.0,17.0,87.58,151.0,-1.6,1.0,0.089431,0.078396,0.179901,0.078479,0.377393
29,MARUTI.NS,107.0,140.0,28.91,80.0,-6.4,0.124396,0.756098,0.69578,0.091811,0.074026,0.353459